_commit: v1.9.0-1-g02b6330
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: grafana
helmRelease: grafana
helmRepo: https://grafana.github.io/helm-charts
helmValues: helm/values.yaml
helmVersion: ''
homepageDescription: Metrics Viewer
homepageEnabled: true
homepageGroup: Kubernetes
homepageIcon: grafana
homepageName: Grafana
ingHost: grafana.crt.house
ingName: grafana
ingress: false
labels: ''
name: grafana
namespace: grafana
pvc: false
reloader: true
resources:
- configmaps.yaml
- external-secrets.yaml
service: false
serviceAccount: false
upstreamURL: https://grafana.com/
url: https://github.com/charlesthomas/homelab-grafana
